spring:
  datasource:
    url: jdbc:mysql://localhost/forohub_api
    username: root
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

   # hibernate:
    #  ddl-auto: update