spring:
  datasource:
    url: jdbc:mysql://localhost/forohub_api
    username: root
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  error:
    include-stacktrace: never

api:
  security:
    jwt:
      secret: ${JWT_SECRECT:2024}
      expiration: 2